[client]

# Controls whether uncaught app exceptions and deprecation warnings
# are displayed in the browser. This can be one of the following:
#
# - "full"       : In the browser, Streamlit displays app deprecation
#                  warnings and exceptions, including exception types,
#                  exception messages, and associated tracebacks.
# - "stacktrace" : In the browser, Streamlit displays exceptions,
#                  including exception types, generic exception messages,
#                  and associated tracebacks. Deprecation warnings and
#                  full exception messages will only print to the
#                  console.
# - "type"       : In the browser, Streamlit displays exception types and
#                  generic exception messages. Deprecation warnings, full
#                  exception messages, and associated tracebacks only
#                  print to the console.
# - "none"       : In the browser, Streamlit displays generic exception
#                  messages. Deprecation warnings, full exception
#                  messages, associated tracebacks, and exception types
#                  will only print to the console.
# - True         : This is deprecated. Streamlit displays "full"
#                  error details.
# - False        : This is deprecated. Streamlit displays "stacktrace"
#                  error details.
#
# Default: "full"
showErrorDetails = "type"


[server]

# Automatically rerun script when the file is modified on disk.
#
# Default: false
runOnSave = true


[browser]

# Whether to send usage statistics to Streamlit.
#
# Default: true
gatherUsageStats = false


[theme]

# The preset Streamlit theme that your custom theme inherits from.
# This can be one of the following: "light" or "dark".
base = "dark"

# Primary accent color.
primaryColor = "#FF3030"

# Background color of the app.
backgroundColor = "#1A1A1A"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#2E2E2E"

# Color used for almost all text.
textColor = "#FFFFFF"

# The font family for all text, except code blocks.
# This can be one of the following:
# - "sans-serif"
# - "serif"
# - "monospace"
# - The `family` value for a custom font table under [[theme.fontFaces]]
# - A comma-separated list of these (as a single string) to specify
#   fallbacks
# For example, you can use the following:
# font = "cool-font, fallback-cool-font, sans-serif"
font = "sans-serif"

# The font family to use for headings.
# This can be one of the following:
# - "sans-serif"
# - "serif"
# - "monospace"
# - The `family` value for a custom font table under [[theme.fontFaces]]
# - A comma-separated list of these (as a single string) to specify
#   fallbacks
# If no heading font is set, Streamlit uses `theme.font` for headings.
headingFont = "sans-serif"

# The radius used as basis for the corners of most UI elements.
# This can be one of the following:
# - "none"
# - "small"
# - "medium"
# - "large"
# - "full"
# - The number in pixels or rem.
# For example, you can use "10px", "0.5rem", or "2rem". To follow best
# practices, use rem instead of pixels when specifying a numeric size.
baseRadius = "large"

# The radius used as basis for the corners of buttons.
# This can be one of the following:
# - "none"
# - "small"
# - "medium"
# - "large"
# - "full"
# - The number in pixels or rem.
# For example, you can use "10px", "0.5rem", or "2rem". To follow best
# practices, use rem instead of pixels when specifying a numeric size.
# If no button radius is set, Streamlit uses `theme.baseRadius` instead.
buttonRadius = "small"

# The color of the border around elements.
borderColor = "#404040"

# Whether to show a border around input widgets.
showWidgetBorder = true